### PR TITLE
Update DHL client to interface with DHL XMLPI endpoint

### PR DESCRIPTION
**Pull request by mpcowan**
I have found that the endpoint the DHL client was communicating with is down, and it's unclear if it is ever coming back up. It appears to be an old endpoint. I have updated it based on DHL's XMLPI interface, which is documented here: https://ratingportal.dhl-usa.com/sites/XMLPI/.

I am not 100% certain whether this would be a breaking change requiring new credentials for those using the only endpoint, but given that it doesn't appear to be working at all right now, it is broken regardless.

### CODE REVIEW

**Comment by sailrish** [comment]
@mpcowan This is super awesome!  Thanks for fixing this.  I'll look it over soon and merge the PR.

**Comment by sailrish** [comment]
@mpcowan I have sent an email to xmlrequests@dhl.com requesting for new credentials for the XML-PI interface.  My old Airborne eCommerce credentials don't work (not surprised).  Once I get that, I should be able to verify your changes work, and then I'll release them.

Btw, was there another way you obtained your DHL XML PI credentials?  There's no easy way it seems, and you likely have to communicate with them over email, etc.

**Comment by mpcowan** [comment]
@sailrish Haha, no it is remarkable. You have to fill out an excel spreadsheet and email that to them. They then email you back credentials. I wish I knew why they do it that way.

**Comment by sailrish** [comment]
I emailed them that spreadsheet, and they responded within the hour.  That's definitely remarkable.  Unfortunately, I don't have a DHL account, and I'll have to email some other department, and wait for them to get presidential approval before they give me an account!

**Comment by sailrish** [comment]
Tested it using this end-point:
http://shipit-api.herokuapp.com/api/carriers/dhl/1276691990

**Comment by sailrish** [comment]
Released in [version 0.6.1](https://www.npmjs.com/package/shipit).

**Comment by sailrish** [comment]
@mpcowan just wondering - are you using shipit to enable the package tracking feature in Trello?  I came across [this](http://blog.trello.com/package-tracking-trello/) in your twitter feed.  If so, I'm happy to see that.

**Comment by mpcowan** [comment]
@sailrish yeah, it definitely saved us a lot of time with that feature. We were happy to be able to contribute back to the project.

**Pull request merged**
